name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun nx format:check --base=origin/main
      - run: bun nx sync:check
      - run: bun nx run-many -t typecheck build -p @org/frontend --parallel=2

      - run: bunx playwright install --with-deps chromium
      - run: bun nx e2e @org/frontend-e2e -- --project=chromium
